#!/bin/sh


case "$1" in
  start|"")
	touch /dev/shm/state
	/home/pi/bin/boil > /dev/shm/boil_log 2>&1 &
	exit $?
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	# No-op
	killall boil
	;;
  *)
	echo "Whatever" >&2
	exit 3
	;;
esac
